[package]
name = "lrc-room-generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lrc-room-generator"
path = "src/main.rs"

[features]
default = ["rust_backend"]
rust_backend = ["flate2/rust_backend"]
zlib-ng = ["flate2/zlib-ng"]

[dependencies]
flate2 = { version = "1", default-features = false }
rayon = "1"
unicode-normalization = "0.1"
memmap2 = "0.9"
zstd = "0.13"
serde_json = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false

[profile.dev]
opt-level = 1