//! Normalization and FNV-1a partition hashing.
//!
//! Must produce byte-identical results to TypeScript `prepareInput` /
//! `hashPartition` (src/types.ts) and Python `normalize` / `fnv1a_hash`
//! (scripts/generate_manifest.py). The three implementations agree on
//! NFKC, lowercasing, the punctuation set, apostrophe removal, and
//! whitespace collapsing.

use unicode_normalization::UnicodeNormalization;

const PUNCT: &[char] = &[
    '`', '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '|',
    '+', '-', '=', '?', ';', ':', '"', ',', '.', '<', '>', '{', '}', '[',
    ']', '\\', '/', '\0', '\n',
];

/// Equivalent of TS `prepareInput` and Python `normalize`.
pub fn prepare_input(text: &str) -> String {
    if text.is_empty() {
        return String::new();
    }

    let nfkc: String = text.nfkc().collect();
    let lower = nfkc.to_lowercase();

    let mut out = String::with_capacity(lower.len());
    for ch in lower.chars() {
        if ch == '\'' || ch == '\u{2019}' {
            continue; // removed entirely
        }
        if PUNCT.contains(&ch) {
            out.push(' ');
        } else {
            out.push(ch);
        }
    }

    // Collapse all Unicode whitespace to single spaces, trim ends.
    out.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Equivalent of TS `hashPartition` and Python `fnv1a_hash`.
pub fn hash_partition(artist_name: &str, track_name: &str, num_rooms: u32) -> u32 {
    let artist = prepare_input(artist_name);
    let track = prepare_input(track_name);
    let key = format!("{} {}", artist, track);
    let bytes = key.as_bytes();

    let mut h: u32 = 0x811c9dc5;
    for &b in bytes {
        h ^= b as u32;
        h = h.wrapping_mul(0x01000193);
    }
    h % num_rooms
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prepare_input_matches_known_values() {
        assert_eq!(prepare_input("Shape of You!"), "shape of you");
        assert_eq!(prepare_input("Don't Stop"), "dont stop");
        assert_eq!(prepare_input("Don\u{2019}t Stop"), "dont stop");
        assert_eq!(prepare_input("\u{FF21}\u{FF22}"), "ab");
        assert_eq!(prepare_input("  a   b  "), "a b");
        assert_eq!(prepare_input(""), "");
    }

    #[test]
    fn hash_matches_typescript_parity_values() {
        // Values from test/types.test.ts, generated by the Python script.
        assert_eq!(hash_partition("Ed Sheeran", "Shape of You", 3200), 1183);
        assert_eq!(hash_partition("Ed Sheeran", "Castle on the Hill", 3200), 711);
        assert_eq!(hash_partition("The Weeknd", "Blinding Lights", 3200), 764);
        assert_eq!(hash_partition("YOASOBI", "\u{30A2}\u{30A4}\u{30C9}\u{30EB}", 3200), 381);
        assert_eq!(hash_partition("YOASOBI", "Monster", 3200), 669);
    }
}