// AUTO-GENERATED by scripts/generate_manifest.py. Do not edit manually.
export const TOTAL_ROOMS = 3439;
export const FILES_PER_ROOM = 4;
export const TOTAL_FILES = 13756;
export const NUM_CHUNKS = 3439;
