// AUTO-GENERATED by scripts/generate_manifest.py. Do not edit manually.
export const TOTAL_ROOMS = 2900;
export const TOTAL_FILES = 11600;
export const NUM_CHUNKS = 2900;
export const NUM_AGGREGATORS = 42;
export const CHUNKS_PER_AGG = 72;
export const NUM_SUPERS = 10;
export const INDEX_FILES = 4;
